"""The Archivist Agent - Living Context Maintainer.

Produces and maintains the system's outputs as living artifacts:
- CODEBASE.md: Living context file for AI agent injection
- onboarding_brief.md: Day-One Brief answering the five FDE questions
- cartography_trace.jsonl: Enhanced audit log
"""

from __future__ import annotations

import json
import logging
from datetime import datetime
from pathlib import Path
from textwrap import dedent

from src.models import DomainCluster, ModuleNode

logger = logging.getLogger(__name__)


class ArchivistAgent:
    """Produces the final deliverable artifacts from all upstream analysis."""

    def __init__(self, repo_path: Path, output_dir: Path):
        self.repo_path = repo_path
        self.output_dir = output_dir

    def run(self, modules: dict[str, ModuleNode],
            surveyor_results: dict, hydrologist_results: dict,
            semanticist_results: dict) -> dict:
        """Generate all output artifacts."""
        logger.info("Archivist: Generating output artifacts")

        codebase_md = self.generate_codebase_md(
            modules, surveyor_results, hydrologist_results, semanticist_results
        )
        onboarding_md = self.generate_onboarding_brief(
            modules, surveyor_results, hydrologist_results, semanticist_results
        )

        # Write artifacts
        self.output_dir.mkdir(parents=True, exist_ok=True)

        codebase_path = self.output_dir / "CODEBASE.md"
        codebase_path.write_text(codebase_md, encoding="utf-8")
        logger.info(f"Archivist: Wrote {codebase_path}")

        onboarding_path = self.output_dir / "onboarding_brief.md"
        onboarding_path.write_text(onboarding_md, encoding="utf-8")
        logger.info(f"Archivist: Wrote {onboarding_path}")

        return {
            "codebase_md_path": str(codebase_path),
            "onboarding_brief_path": str(onboarding_path),
            "codebase_md_length": len(codebase_md),
            "onboarding_brief_length": len(onboarding_md),
        }

    # CODEBASE.md Generation

    def generate_codebase_md(self, modules: dict[str, ModuleNode],
                              surveyor_results: dict, hydrologist_results: dict,
                              semanticist_results: dict) -> str:
        """Generate the CODEBASE.md living context file.

        Structured for direct injection into AI coding agents.
        """
        sections = []

        # Header
        sections.append(self._header_section())

        # Architecture Overview
        sections.append(self._architecture_overview(
            modules, surveyor_results, hydrologist_results
        ))

        # Critical Path
        sections.append(self._critical_path_section(modules))

        # Data Sources & Sinks
        sections.append(self._data_sources_sinks_section(hydrologist_results))

        # Known Debt
        sections.append(self._known_debt_section(
            surveyor_results, semanticist_results
        ))

        # High-Velocity Files
        sections.append(self._high_velocity_section(surveyor_results))

        # Module Purpose Index
        sections.append(self._module_purpose_index(
            modules, semanticist_results
        ))

        return "\n\n".join(sections)

    def _header_section(self) -> str:
        repo_name = self.repo_path.name
        return dedent(f"""\
            # CODEBASE.md — {repo_name}

            > Auto-generated by The Brownfield Cartographer
            > Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}
            > Target: {self.repo_path}
            >
            > This file provides architectural context for AI coding agents.
            > Inject this as system prompt context for instant codebase awareness.""")

    def _architecture_overview(self, modules: dict[str, ModuleNode],
                                surveyor_results: dict,
                                hydrologist_results: dict) -> str:
        # Language breakdown
        lang_counts: dict[str, int] = {}
        for mod in modules.values():
            lang_counts[mod.language.value] = lang_counts.get(mod.language.value, 0) + 1
        lang_str = ", ".join(
            f"{lang} ({count})" for lang, count in
            sorted(lang_counts.items(), key=lambda x: -x[1])
        )

        # Domain breakdown
        domain_counts: dict[str, int] = {}
        for mod in modules.values():
            d = mod.domain_cluster.value
            domain_counts[d] = domain_counts.get(d, 0) + 1
        domain_str = ", ".join(
            f"{domain} ({count})" for domain, count in
            sorted(domain_counts.items(), key=lambda x: -x[1])
        )

        total_functions = len(surveyor_results.get("functions", {}))
        datasets = hydrologist_results.get("datasets", {})
        transformations = hydrologist_results.get("transformations", {})

        return dedent(f"""\
            ## Architecture Overview

            This codebase contains **{len(modules)} modules** across {lang_str}.

            **Domain Distribution:** {domain_str}

            **Data Layer:** {len(datasets)} datasets, {len(transformations)} transformations tracked in the data lineage graph.

            **Code Surface:** {total_functions} functions extracted via static analysis.""")

    def _critical_path_section(self, modules: dict[str, ModuleNode]) -> str:
        """Top 5 modules by PageRank — the architectural hubs."""
        top = sorted(
            modules.items(), key=lambda x: x[1].pagerank_score, reverse=True
        )[:10]

        lines = ["## Critical Path (Top Modules by PageRank)", ""]
        lines.append("These modules are the most-imported architectural hubs. "
                     "Changes here have the widest impact.")
        lines.append("")
        lines.append("| Rank | Module | PageRank | Domain | LOC | Purpose |")
        lines.append("|------|--------|----------|--------|-----|---------|")

        for i, (path, mod) in enumerate(top, 1):
            purpose = (mod.purpose_statement or "")[:80]
            lines.append(
                f"| {i} | `{path}` | {mod.pagerank_score:.4f} | "
                f"{mod.domain_cluster.value} | {mod.lines_of_code} | {purpose} |"
            )

        return "\n".join(lines)

    def _data_sources_sinks_section(self, hydrologist_results: dict) -> str:
        """Data entry and exit points."""
        sources = hydrologist_results.get("sources", [])
        sinks = hydrologist_results.get("sinks", [])

        lines = ["## Data Sources & Sinks", ""]

        lines.append(f"### Sources ({len(sources)} entry points)")
        lines.append("These are the ultimate data origins — nodes with no upstream dependencies.")
        lines.append("")
        for s in sources[:20]:
            lines.append(f"- `{s}`")
        if len(sources) > 20:
            lines.append(f"- ... and {len(sources) - 20} more")

        lines.append("")
        lines.append(f"### Sinks ({len(sinks)} terminal outputs)")
        lines.append("These are the final output datasets — nodes with no downstream consumers.")
        lines.append("")
        for s in sinks[:20]:
            lines.append(f"- `{s}`")
        if len(sinks) > 20:
            lines.append(f"- ... and {len(sinks) - 20} more")

        return "\n".join(lines)

    def _known_debt_section(self, surveyor_results: dict,
                             semanticist_results: dict) -> str:
        """Circular dependencies + documentation drift."""
        lines = ["## Known Debt", ""]

        # Circular dependencies
        circular = surveyor_results.get("circular_dependencies", [])
        lines.append(f"### Circular Dependencies ({len(circular)} detected)")
        if circular:
            for dep in circular[:10]:
                cycle_str = " → ".join(dep.cycle) + " → " + dep.cycle[0]
                lines.append(f"- ⚠ {cycle_str} (severity: {dep.severity})")
        else:
            lines.append("None detected. ✅")

        # Dead code
        dead = surveyor_results.get("dead_code_candidates", [])
        lines.append("")
        lines.append(f"### Dead Code Candidates ({len(dead)} modules)")
        if dead:
            lines.append("Modules never imported by any other file (may be entry points):")
            for d in dead[:15]:
                lines.append(f"- `{d}`")
            if len(dead) > 15:
                lines.append(f"- ... and {len(dead) - 15} more")
        else:
            lines.append("None detected. ✅")

        # Documentation drift
        drift = semanticist_results.get("doc_drift_flags", {})
        lines.append("")
        lines.append(f"### Documentation Drift ({len(drift)} flags)")
        if drift:
            lines.append(
                "Modules where the docstring appears to contradict the implementation:"
            )
            for path, issue in list(drift.items())[:10]:
                lines.append(f"- `{path}`: {issue}")
        else:
            lines.append("No drift detected (or LLM analysis not performed). ✅")

        return "\n".join(lines)

    def _high_velocity_section(self, surveyor_results: dict) -> str:
        """Files changing most frequently = likely pain points."""
        velocity = surveyor_results.get("git_velocity", [])
        hot_files = surveyor_results.get("high_velocity_80_20", [])

        lines = ["## High-Velocity Files (Recent Change Activity)", ""]

        if hot_files:
            lines.append(
                f"**80/20 Rule:** {len(hot_files)} files account for 80%+ of all commits."
            )
            lines.append("")

        lines.append("| File | Commits (30d) | Cumulative % |")
        lines.append("|------|--------------|--------------|")

        if hot_files:
            for hf in hot_files[:15]:
                lines.append(f"| `{hf['path']}` | {hf['commits']} | {hf['cumulative_pct']}% |")
        elif velocity:
            total = sum(v.commit_count_30d for v in velocity)
            cumulative = 0
            for v in velocity[:15]:
                if v.commit_count_30d == 0:
                    break
                cumulative += v.commit_count_30d
                pct = round(cumulative / total * 100, 1) if total > 0 else 0
                lines.append(f"| `{v.path}` | {v.commit_count_30d} | {pct}% |")
        else:
            lines.append("| (no git data available) | - | - |")

        return "\n".join(lines)

    def _module_purpose_index(self, modules: dict[str, ModuleNode],
                               semanticist_results: dict) -> str:
        """Purpose statement index for every analyzed module."""
        purposes = semanticist_results.get("purpose_statements", {})

        lines = ["## Module Purpose Index", ""]
        lines.append("Purpose statements for key modules (by architectural significance):")
        lines.append("")

        # Sort by PageRank
        sorted_mods = sorted(
            modules.items(), key=lambda x: x[1].pagerank_score, reverse=True
        )

        for path, mod in sorted_mods[:30]:
            purpose = purposes.get(path, mod.purpose_statement or "")
            if purpose:
                lines.append(f"### `{path}`")
                lines.append(f"- **Domain:** {mod.domain_cluster.value}")
                lines.append(f"- **Language:** {mod.language.value}")
                lines.append(f"- **LOC:** {mod.lines_of_code}")
                lines.append(f"- **Purpose:** {purpose}")
                lines.append("")

        return "\n".join(lines)

    # Onboarding Brief Generation

    def generate_onboarding_brief(self, modules: dict[str, ModuleNode],
                                   surveyor_results: dict,
                                   hydrologist_results: dict,
                                   semanticist_results: dict) -> str:
        """Generate the FDE Day-One Onboarding Brief."""
        repo_name = self.repo_path.name
        day_one_answers = semanticist_results.get("day_one_answers", {})

        sections = []

        # Header
        sections.append(dedent(f"""\
            # FDE Day-One Onboarding Brief — {repo_name}

            > Auto-generated by The Brownfield Cartographer
            > Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}
            > Target: {self.repo_path}
            >
            > This brief answers the five critical questions every FDE needs answered
            > within 72 hours of a new engagement."""))

        # Quick Stats
        lang_counts: dict[str, int] = {}
        for mod in modules.values():
            lang_counts[mod.language.value] = lang_counts.get(mod.language.value, 0) + 1

        datasets = hydrologist_results.get("datasets", {})
        sections.append(dedent(f"""\
            ## Quick Stats

            | Metric | Value |
            |--------|-------|
            | Total modules | {len(modules)} |
            | Total datasets | {len(datasets)} |
            | Languages | {', '.join(f'{l} ({c})' for l, c in sorted(lang_counts.items(), key=lambda x: -x[1]))} |
            | Analysis timestamp | {datetime.now().strftime('%Y-%m-%d %H:%M')} |"""))

        # Day-One Questions
        sections.append("## The Five FDE Day-One Questions\n")

        question_labels = {
            "Q1": "Q1: What is the primary data ingestion path?",
            "Q2": "Q2: What are the 3-5 most critical output datasets/endpoints?",
            "Q3": "Q3: What is the blast radius if the most critical module fails?",
            "Q4": "Q4: Where is the business logic concentrated vs. distributed?",
            "Q5": "Q5: What has changed most frequently in the last 90 days?",
        }

        for key, label in question_labels.items():
            answer = day_one_answers.get(key, "_No answer generated._")
            sections.append(f"### {label}\n\n{answer}\n")

        # Critical Architecture Points
        top_modules = sorted(
            modules.items(), key=lambda x: x[1].pagerank_score, reverse=True
        )[:5]

        sections.append("## Critical Architecture Points\n")
        sections.append("### Architectural Hubs (Highest PageRank)\n")
        for path, mod in top_modules:
            purpose = mod.purpose_statement or ""
            sections.append(
                f"- **`{path}`** (PageRank: {mod.pagerank_score:.4f}) — {purpose}"
            )

        # Known Risks
        sections.append("\n### Known Risks\n")
        circular = surveyor_results.get("circular_dependencies", [])
        dead = surveyor_results.get("dead_code_candidates", [])
        drift = semanticist_results.get("doc_drift_flags", {})

        sections.append(f"- **Circular dependencies:** {len(circular)}")
        sections.append(f"- **Dead code candidates:** {len(dead)}")
        sections.append(f"- **Documentation drift flags:** {len(drift)}")

        # Budget summary
        budget = semanticist_results.get("budget_summary", {})
        if budget:
            sections.append("\n## Analysis Cost Summary\n")
            sections.append(f"- LLM calls: {budget.get('total_calls', 0)}")
            sections.append(f"- Tokens used: {budget.get('total_tokens_used', 0):,}")
            sections.append(f"- Estimated cost: ${budget.get('total_cost_usd', 0):.4f}")

        return "\n\n".join(sections)
